package core.lexer;

public enum Section {
    UNDETERMINED,
    HEADING_MARKER, HEADING_SPACE,
    IDENTIFIER, TEXT,

    TAG_START, TAG_IDENTIFIER, TAG_WHITESPACE, TAG_ATTRIBUTE, TAG_ATTRIBUTE_EQUALS, TAG_END
}